### ISSUE TITLE
remove readme instruction on switching from main branch after July 2021

### ISSUE THREAD

**Issue by fmichaelobrien** [canada-ca/accelerators_accelerateurs-gcp#3]

**Comment by fmichaelobrien** [comment]
remove
"git checkout landingzone-update # temp until merged into main"
from
https://github.com/canada-ca/accelerators_accelerateurs-gcp/blob/main/deployment-templates/Terraform/guardrails/README.md?plain=1#L27

**Comment by ptd-tbs** [comment]
Done.
